library:
  source-dirs: src
tests:
  eulerplate-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eulerplate
copyright: 2018 Kit Langton
maintainer: kitlangton@gmail.com
dependencies:
- vector
- attoparsec
- base >= 4.7 && < 5
- wreq
- turtle
- lens
- bytestring
- text
- tagsoup
- system-filepath
- configurator
- zip
- containers
- managed
- shakespeare
- casing
- mtl
- optparse-applicative
- yaml
- lens-aeson
- unordered-containers
name: eulerplate
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Kit Langton
github: kitlangton/eulerplate
license: BSD3
executables:
  eulerplate-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eulerplate
description: Please see the README on GitHub at <https://github.com/githubuser/eulerplate#readme>
